### ISSUE TITLE
Some question about the punctuation?

### ISSUE THREAD

**Issue by caoxu915683474** [jind11/word2vec-on-wikipedia#2]
Hi, jind11! 
Thanks for your great work! How can I get the article raw corpus with your extracted? What parameters should I set? 

Thank you!

**Comment by jind11** [comment]
Here is the link to download the wikipedia pages: https://dumps.wikimedia.org/enwiki/latest/. Here are the most used hyperparameters: -window 10 -negative 15 -hs 0 -sample 1e-5.
